/**
 * Disbursement export utilities: CSV, PDF (dynamic jsPDF import) and email.
 * Pure DOM/IO layer — no React. Output is byte-compatible with the legacy page
 * implementations (two PDF variants preserved deliberately).
 */
import { buildCsv, downloadCsv, todayFileStamp } from '@/lib/csv';
import type { DisbursementRaw } from '@/models/Disbursement';

const REPORT_TITLE = 'NYANTRA - Disbursements Report';
const REPORT_SUBTITLE = 'Direct Benefit Transfer System under PCR & PoA Acts';
const FOOTER_TEXT = 'This report is generated by Nyantra - Direct Benefit Transfer System';

const BRAND_BLUE = { r: 30, g: 64, b: 175 } as const;
function rgb({ r, g, b }: typeof BRAND_BLUE): [number, number, number] {
  return [r, g, b];
}

export const DISBURSEMENT_CSV_HEADERS = [
  'Disbursement ID',
  'Beneficiary ID',
  'Beneficiary Name',
  'Aadhaar',
  'Phone',
  'District',
  'State',
  'Act Type',
  'Case Number',
  'Relief Amount',
  'Disbursed Amount',
  'Net Amount',
  'Status',
  'Transaction ID',
  'Initiated Date', // replaced by the translated label at call time
  'Disbursement Date',
] as const;

export function buildDisbursementCsv(
  items: readonly DisbursementRaw[],
  initiatedDateLabel: string,
): string {
  const headers = DISBURSEMENT_CSV_HEADERS.map((h) =>
    h === 'Initiated Date' ? (initiatedDateLabel || 'Initiated Date') : h,
  );
  const rows = items.map((d) => [
    d.id,
    d.beneficiaryId,
    d.beneficiaryName,
    d.aadhaarNumber,
    d.phone,
    d.district,
    d.state,
    d.actType,
    d.caseNumber,
    d.reliefAmount,
    d.disbursedAmount,
    d.netAmount,
    d.status,
    d.transactionId,
    d.initiatedDate,
    d.disbursementDate,
  ]);
  return buildCsv(headers, rows);
}

export function downloadDisbursementsCsv(
  items: readonly DisbursementRaw[],
  initiatedDateLabel: string,
): void {
  downloadCsv(
    buildDisbursementCsv(items, initiatedDateLabel),
    `disbursements_export_${todayFileStamp()}.csv`,
  );
}

type JsPdfDoc = import('jspdf').jsPDF;

interface PdfTableColumn {
  header: string;
  width: number;
  dataKey?: string;
}

/** Shared chrome: blue header band + footer line. */
async function drawReportChrome(doc: JsPdfDoc, items: readonly DisbursementRaw[]): Promise<number> {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;

  doc.setFillColor(...rgb(BRAND_BLUE));
  doc.rect(0, 0, pageWidth, 35, 'F');

  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text(REPORT_TITLE, margin, 22);

  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'normal');
  doc.text(REPORT_SUBTITLE, margin, 30);

  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  const currentDate = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
  doc.text(`Generated: ${currentDate}`, pageWidth - margin, 22, { align: 'right' });
  doc.text(`Total Records: ${items.length}`, pageWidth - margin, 30, { align: 'right' });

  return 50; // starting yPosition for content
}

function drawFooter(doc: JsPdfDoc, fontSize: number): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const footerY = pageHeight - 15;
  doc.setFontSize(fontSize);
  doc.setTextColor(128, 128, 128);
  doc.setFont('helvetica', 'italic');
  doc.text(FOOTER_TEXT, margin, footerY);
  doc.text('Page 1 of 1', pageWidth - margin, footerY, { align: 'right' });
}

function drawTableHeader(
  doc: JsPdfDoc,
  columns: PdfTableColumn[],
  yPosition: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  doc.setFillColor(...rgb(BRAND_BLUE));
  doc.rect(margin, yPosition, pageWidth - margin * 2, 8, 'F');
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  let xPos = margin + 2;
  columns.forEach((col) => {
    doc.text(col.header, xPos, yPosition + 5.5);
    xPos += col.width;
  });
  return yPosition + 10;
}

/**
 * Download-variant PDF (progressive amounts, status breakdown with %).
 */
export async function exportDisbursementsPdf(items: readonly DisbursementRaw[]): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  let yPosition = await drawReportChrome(doc, items);

  // Summary section
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, yPosition, contentWidth, 25, 'F');
  doc.setFontSize(12);
  doc.setTextColor(...rgb(BRAND_BLUE));
  doc.setFont('helvetica', 'bold');
  doc.text('EXECUTIVE SUMMARY', margin + 5, yPosition + 8);

  const totalAmount = items.reduce((sum, d) => sum + (d.reliefAmount || 0), 0);
  const statusCounts = items.reduce((acc, d) => {
    const key = d.status ?? '';
    acc[key] = (acc[key] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Disbursements: ${items.length}`, margin + 5, yPosition + 18);
  doc.text(`Total Amount: ₹${totalAmount.toLocaleString('en-IN')}`, pageWidth - margin - 5, yPosition + 18, { align: 'right' });

  yPosition += 35;

  // Status breakdown
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...rgb(BRAND_BLUE));
  doc.text('Status Breakdown:', margin, yPosition);

  yPosition += 8;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);

  Object.entries(statusCounts).forEach(([status, count]) => {
    const statusText = status.replace(/-/g, ' ').toUpperCase();
    const percentage = ((count / items.length) * 100).toFixed(1);
    doc.text(`${statusText}: ${count} (${percentage}%)`, margin + 5, yPosition);
    yPosition += 5;
  });

  yPosition += 10;

  const tableColumns: PdfTableColumn[] = [
    { header: 'Disbursement ID', width: 30, dataKey: 'id' },
    { header: 'Beneficiary', width: 35, dataKey: 'beneficiaryName' },
    { header: 'District', width: 25, dataKey: 'district' },
    { header: 'Act Type', width: 25, dataKey: 'actType' },
    { header: 'Amount (₹)', width: 25, dataKey: 'reliefAmount' },
    { header: 'Status', width: 25, dataKey: 'status' },
    { header: 'Transaction ID', width: 30, dataKey: 'transactionId' },
  ];

  const tableRows = items.map((d) => ({
    id: d.id || '',
    beneficiaryName: d.beneficiaryName || '',
    district: d.district || '',
    actType: d.actType || '',
    reliefAmount:
      d.isProgressivePayment
        ? `₹${d.netAmount?.toLocaleString('en-IN') || 0} (${d.disbursementProgress || 0}% complete)`
        : `₹${d.reliefAmount?.toLocaleString('en-IN') || 0}`,
    status: (d.status || '').toUpperCase(),
    transactionId: d.transactionId || 'N/A',
  }));

  if (yPosition > pageHeight - 60) {
    doc.addPage();
    yPosition = margin;
  }

  yPosition = drawTableHeader(doc, tableColumns, yPosition);

  doc.setFontSize(7);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');

  tableRows.forEach((row, index) => {
    if (yPosition > pageHeight - 20) {
      doc.addPage();
      yPosition = drawTableHeader(doc, tableColumns, margin);
      doc.setFontSize(7);
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'normal');
    }

    if (index % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, yPosition - 3, contentWidth, 6, 'F');
    }

    let xPos = margin + 2;
    tableColumns.forEach((col) => {
      const key = col.dataKey as keyof typeof row;
      const value = row[key] ?? '';
      doc.text(String(value), xPos, yPosition + 2);
      xPos += col.width;
    });

    yPosition += 6;
  });

  drawFooter(doc, 6);
  doc.save(`nyantra_disbursements_report_${todayFileStamp()}.pdf`);
}

/**
 * Email-variant PDF. Reproduces the legacy attachment byte-for-byte,
 * including its summary lines and column layout (empty 'Amount' cell quirk
 * preserved — see refactor notes).
 */
export async function buildDisbursementsPdfForEmail(
  items: readonly DisbursementRaw[],
): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf');
  const pdfDoc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  const pageWidth = pdfDoc.internal.pageSize.getWidth();
  const pageHeight = pdfDoc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  let yPosition = await drawReportChrome(pdfDoc, items);

  // Summary section
  pdfDoc.setFillColor(240, 240, 240);
  pdfDoc.rect(margin, yPosition, contentWidth, 25, 'F');
  pdfDoc.setFontSize(12);
  pdfDoc.setTextColor(...rgb(BRAND_BLUE));
  pdfDoc.setFont('helvetica', 'bold');
  pdfDoc.text('EXECUTIVE SUMMARY', margin + 5, yPosition + 8);

  const totalAmount = items.reduce((sum, d) => sum + (d.reliefAmount || 0), 0);
  const completedCount = items.filter((d) => d.status === 'completed').length;
  const pendingCount = items.filter((d) => d.status === 'pending').length;
  const failedCount = items.filter((d) => d.status === 'failed').length;

  pdfDoc.setFontSize(9);
  pdfDoc.setTextColor(0, 0, 0);
  pdfDoc.setFont('helvetica', 'normal');
  pdfDoc.text(`Total Disbursements: ₹${totalAmount.toLocaleString('en-IN')}`, margin + 5, yPosition + 18);
  pdfDoc.text(
    `Completed: ${completedCount} | Pending: ${pendingCount} | Failed: ${failedCount}`,
    margin + 5,
    yPosition + 25,
  );

  yPosition += 35;

  const tableColumns: PdfTableColumn[] = [
    { header: 'ID', width: 25 },
    { header: 'Beneficiary', width: 40 },
    { header: 'District', width: 30 },
    { header: 'Act Type', width: 25 },
    { header: 'Amount', width: 25 },
    { header: 'Status', width: 20 },
    { header: 'Transaction ID', width: 35 },
  ];

  const tableRows = items.map((d) => ({
    id: d.id || '',
    beneficiaryName: d.beneficiaryName || '',
    district: d.district || '',
    actType: d.actType || '',
    reliefAmount: d.reliefAmount ? `₹${d.reliefAmount.toLocaleString('en-IN')}` : '₹0',
    status: (d.status || '').toUpperCase(),
    transactionId: d.transactionId || 'N/A',
  }));

  yPosition = drawTableHeader(pdfDoc, tableColumns, yPosition);

  pdfDoc.setFontSize(7);
  pdfDoc.setTextColor(0, 0, 0);
  pdfDoc.setFont('helvetica', 'normal');

  tableRows.forEach((row) => {
    if (yPosition > pageHeight - 20) {
      pdfDoc.addPage();
      yPosition = drawTableHeader(pdfDoc, tableColumns, margin);
      pdfDoc.setFontSize(7);
      pdfDoc.setTextColor(0, 0, 0);
      pdfDoc.setFont('helvetica', 'normal');
    }

    let xPos = margin + 2;
    tableColumns.forEach((col) => {
      // Legacy lookup: header-derived key ('amount') never matches the row keys.
      const key = col.header.toLowerCase().replace(' ', '') as keyof typeof row;
      const value = row[key] ?? '';
      pdfDoc.text(String(value), xPos, yPosition + 3);
      xPos += col.width;
    });

    yPosition += 6;
  });

  drawFooter(pdfDoc, 8);
  return pdfDoc.output('arraybuffer');
}

function buildDisbursementsEmailHtml(items: readonly DisbursementRaw[], format: string): string {
  const generated = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
  return `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
              <h2 style="color: #1e40af;">Nyantra - Disbursements Report</h2>
              <p>Dear User,</p>
              <p>Please find attached the disbursements report containing ${items.length} records.</p>
              <p><strong>Report Details:</strong></p>
              <ul>
                <li>Total Records: ${items.length}</li>
                <li>Format: ${format.toUpperCase()}</li>
                <li>Generated: ${generated}</li>
              </ul>
              <p>This report is generated by the Nyantra Direct Benefit Transfer System.</p>
              <p>Best regards,<br>Nyantra Team</p>
            </div>
          `;
}

export interface EmailDispatchResult {
  ok: boolean;
}

/** Sends the report via /api/send-email exactly like the legacy flow. */
export async function sendDisbursementsEmail(
  items: readonly DisbursementRaw[],
  format: 'csv' | 'pdf',
  emailAddress: string,
  initiatedDateLabel: string,
): Promise<EmailDispatchResult> {
  let attachmentData: string | Buffer;
  let attachmentName: string;
  let attachmentType: string;

  if (format === 'csv') {
    attachmentData = buildDisbursementCsv(items, initiatedDateLabel);
    attachmentName = `nyantra_disbursements_report_${todayFileStamp()}.csv`;
    attachmentType = 'text/csv';
  } else {
    const arrayBuffer = await buildDisbursementsPdfForEmail(items);
    // Preserved legacy behaviour (Buffer over ArrayBuffer).
    attachmentData = Buffer.from(arrayBuffer);
    attachmentName = `nyantra_disbursements_report_${todayFileStamp()}.pdf`;
    attachmentType = 'application/pdf';
  }

  const response = await fetch('/api/send-email', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      to: emailAddress,
      subject: `Nyantra Disbursements Report - ${new Date().toLocaleDateString()}`,
      html: buildDisbursementsEmailHtml(items, format),
      attachments: [
        {
          filename: attachmentName,
          content: attachmentData,
          contentType: attachmentType,
          encoding: format === 'csv' ? 'utf8' : undefined,
        },
      ],
    }),
  });

  if (!response.ok) throw new Error('Failed to send email');
  return { ok: true };
}
