name: i18n-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run i18n import checker
        run: npm run lint:i18n
      - name: Run i18n parity test
        run: npm run test:i18n
